- name: provisioning
  hosts: all
  remote_user: root
  tasks:

  - name: Install required base applications
    apt: name={{ item }} state=latest allow_unauthenticated=yes cache_valid_time=3600
    with_items:
      - build-essential
      - git
      - htop
      - realpath
      - gimp 
      - libreoffice
      - gdebi
      - virtualbox-guest-dkms 
      - virtualbox-guest-utils 
      - chromium-browser
    become: true